#!/bin/bash

echo "Compiling"

if [ ! $# -eq 2 ]
  then
    echo "Input 1 = Compile source"
    echo "Input 2 = Output target"
fi

/opt/riscv/bin/riscv32-unknown-elf-gcc $1 -o $2
/opt/riscv/bin/riscv32-unknown-elf-gcc $1 -S -o $2.S